[package]
name = "kernel"
version = "0.1.0"
edition = "2018"

[dependencies]
vm-memory = { git = "https://github.com/EmeraldShift/vm-memory", features = ["backend-mmap"] }

utils = { path = "../utils" }
